### ISSUE TITLE
Chat client disconnects when app is in background, "Socket is not connected"

### ISSUE THREAD

**Issue by silajdzice** [twilio/twilio-chat-ios#25]
Hi,

We are implementing the Twilio iOS Chat SDK, when the app is sent to the background or left in the foreground idle for a long time.

Is there something we need to do to ensure the client doesn't timeout over long periods of execution? 

After this happens and client send a message I can see the console logs "Socket is not connected".  Not sure what is causing this, everything works ok on older version (3.1.0) .

Thanks and have a nice day, Edhem iOS developer.

**Comment by Gray-Wind** [comment]
Hello, we have just released 4.2.0 version, please try it out, this issue has been fixed there.

Please give me know if it would work for you.

**Comment by silajdzice** [comment]
Hey @Gray-Wind , thanks for quick reply. 

Unfortunately I can confirm that I upgraded TwilioChat to 4.2.0 version and there is still the same issue. Any ideas why ?

**Comment by Gray-Wind** [comment]
Hello,
Could you provide logs from the SDK it would help us to understand why connection was dropped?
It is possible to do [by setting logLevel](https://media.twiliocdn.com/sdk/ios/chat/releases/4.2.0/docs/Classes/TwilioChatClient.html#//api/name/setLogLevel:).
You can either upload them and paste a link here, or (even better) create [a new support ticket](https://support.twilio.com/hc/en-us/requests/new), and upload logs there.

**Comment by silajdzice** [comment]
@Gray-Wind Hey again, I'll paste some logs I get when reproducing this issue.

2021-03-24 16:04:36560 [🔬][HomeViewController.swift]:90 14 appMovedToForeground() -> App moved to ForeGround!
2021-03-24 16:04:36.668843+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C1.1 104.18.225.52:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.669006+0100 Sama[7649:1906465] [connection] nw_write_request_report [C1] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.669281+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C1.1 104.18.225.52:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.669982+0100 Sama[7649:1906465] [connection] nw_write_request_report [C1] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.670166+0100 Sama[7649:1906465] [connection] nw_connection_copy_connected_local_endpoint [C1] Connection has no local endpoint
2021-03-24 16:04:36.670595+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C3.1 34.96.125.79:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.670899+0100 Sama[7649:1906465] [connection] nw_write_request_report [C3] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.670952+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C3.1 34.96.125.79:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.670985+0100 Sama[7649:1906465] [connection] nw_write_request_report [C3] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.671963+0100 Sama[7649:1906465] [connection] nw_connection_copy_connected_local_endpoint [C3] Connection has no local endpoint
2021-03-24 16:04:36.672873+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C4.1 172.67.215.209:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.672910+0100 Sama[7649:1906465] [connection] nw_write_request_report [C4] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.674909+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C4.1 172.67.215.209:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.675059+0100 Sama[7649:1906465] [connection] nw_write_request_report [C4] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.675192+0100 Sama[7649:1906465] [connection] nw_connection_copy_connected_local_endpoint [C4] Connection has no local endpoint
2021-03-24 16:04:36.678744+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C5.1 172.217.18.74:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.679283+0100 Sama[7649:1906465] [connection] nw_write_request_report [C5] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.686564+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C5.1 172.217.18.74:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.701679+0100 Sama[7649:1906465] [connection] nw_write_request_report [C5] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.706146+0100 Sama[7649:1906465] [connection] nw_connection_copy_connected_local_endpoint [C5] Connection has no local endpoint
2021-03-24 16:04:36.712964+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C8.1 172.67.215.209:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.713009+0100 Sama[7649:1906465] [connection] nw_write_request_report [C8] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.713068+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C8.1 172.67.215.209:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.713095+0100 Sama[7649:1906465] [connection] nw_write_request_report [C8] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.713170+0100 Sama[7649:1906465] [connection] nw_connection_copy_connected_local_endpoint [C8] Connection has no local endpoint
2021-03-24 16:04:36.713786+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C9.1 104.18.225.52:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.713866+0100 Sama[7649:1906465] [connection] nw_write_request_report [C9] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.714056+0100 Sama[7649:1906465] [connection] nw_flow_add_write_request [C9.1 104.18.225.52:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:04:36.714152+0100 Sama[7649:1906465] [connection] nw_write_request_report [C9] Send failed with error "Socket is not connected"
2021-03-24 16:04:36.714640+0100 Sama[7649:1906465] [connection] nw_connection_copy_connected_local_endpoint [C9] Connection has no local endpoint
2021-03-24 16:04:36.728526+0100 Sama[7649:1906465] Connection 7: encountered error(1:53)
2021-03-24 16:04:36.728676+0100 Sama[7649:1906465] Connection 7: received failure notification

2021-03-24 16:05:18.522047+0100 Sama[7649:1912843] [connection] nw_flow_add_write_request [C7.1 52.205.125.54:443 failed channel-flow (satisfied (Path is satisfied), interface: en0, ipv4, dns)] cannot accept write requests
2021-03-24 16:05:18.522281+0100 Sama[7649:1912843] [connection] nw_write_request_report [C7] Send failed with error "Socket is not connected"
2021-03-24 16:05:18.523372+0100 Sama[7649:1912848] [connection] nw_connection_copy_connected_local_endpoint [C7] Connection has no local endpoint
2021-03-24 16:05:18.524818+0100 Sama[7649:1912847] [websocket] Read completed with an error Operation canceled

**Comment by Gray-Wind** [comment]
Thank you very much for logs. I would like to see all logs if it possible.

You can also send all logs to ikolomeitsev@twilio.com, if it is better option for you.

**Comment by Gray-Wind** [comment]
From the logs I can see that client is being deinitialised when application goes background. The application should hold the strong link to the client, it should not be shut down or destroyed, otherwise it should be re-created, which is not recommended.

More best practices could be found [here](https://www.twilio.com/docs/chat/best-practices-sdk-clients).

I'm closing this issue, feel free to create a new one if you feel a need.
